// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9MzrY014eHkCdCsvkRhWvd_IGzeqFLo',
    appId: '1:895363444505:web:8bc1cfafa329b29c3cdf88',
    messagingSenderId: '895363444505',
    projectId: 'my-ecommerce-app-123-e4619',
    authDomain: 'my-ecommerce-app-123-e4619.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-e4619.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3bSRHcqoqmIu6YCCWXgzxZc-8w0lSMs',
    appId: '1:895363444505:android:c3588f19b128a3953cdf88',
    messagingSenderId: '895363444505',
    projectId: 'my-ecommerce-app-123-e4619',
    storageBucket: 'my-ecommerce-app-123-e4619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBg3VRHB1XMFSaYSDOneQuJE4uI-VB1D4',
    appId: '1:895363444505:ios:d2102a8e1b2358043cdf88',
    messagingSenderId: '895363444505',
    projectId: 'my-ecommerce-app-123-e4619',
    storageBucket: 'my-ecommerce-app-123-e4619.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
